<h1 align="center">Zewail University of Science and Technology</h1>
<h2 align="center">CIE 553 (Spring 2019)</h2>
<h2 align="center">Lab 1: Python Tutorial</h3>
<h3 align="center">31/01/2019</h3>

### Dynamically Typed Language

In [0]:
x = 1 #x is bound to a value of type int
x *= 2.1 #x is now bound to another value of type float
print (x)

2.1


In [2]:
# every variable is a name binded to an object not a pointer
# we pass the objects to functions by reference
# here when c = a we bind c to the same object as a thus changing c changes a
a = [1,2,3,4]
def foo(a):
  c = a
  c.append(5)
  # if we make c = [4,5,6] we bind c to a new object and thus a remains the same
  return c,a
b = foo(a)
b
# this help with two main things:
# 1) no variable type
# 2) Garbage collection (if No name binds to an object, gc removes the object from memory)

([1, 2, 3, 4, 5], [1, 2, 3, 4, 5])

In [4]:
# small integers get stored as only 1 object and all variables binds to them for fast access
a = 5
b = a
print(id(a))
#b = 5
print(id(b))

1818782912
1818782912


### Conditional

In [5]:
x = 2
y = 1

if x == y:
    print("x equals y")
elif x > y:
    print ("x is greater than y")
else:
    print ("x is smaller than y")

x is greater than y


### Strings

In [6]:
x = "This is a single \
line written in two lines"  # \ is used to continue the statement in another line
print(x)

This is a single line written in two lines


In [7]:
x = '''This is a
three
    lines
        statement'''
print(x)

This is a
three
    lines
        statement


In [8]:
x = 'Hello World' 
print(x[0:5]) #strings are indexable

Hello


In [9]:
x = "20"
y = "18"
print(x + y) #strings can be concatenated using + operator

2018


In [11]:
'20'+str(18)

'2018'

In [12]:
#non-string objects can be converted to strings using str() or format()
x = "20"
y = 18
print(x + str(y))
print(x + format(y, "0.2f"))
print(x + format(y, "d"))

2018
2018.00
2018


In [15]:
x = "Hello"
x[1] = 's' #strings are immutable

TypeError: 'str' object does not support item assignment

In [16]:
# string formating
name = 'jo'
age = 23
s = "Hello %s\nyou are %s old" % (name, age)
s = "Hello {1}\nyou are {0} old".format(age,name)
s = f"Hello {name}\nyou are {age} old"
print(s)
pi = 3.14159265359
s = f"pi equals |{pi:*^15.3f}|"
print(s)

Hello jo
you are 23 old
pi equals |*****3.142*****|


### Lists

In [17]:
x = ["Hello", "World", "."]

In [18]:
#lists are indexable
print (x[0])

Hello


In [19]:
#lists are mutable
print (x[2])
x[2] = "!"
print (x[2])

.
!


In [0]:
#appending items at the end
x.append("!")
print (x)

['Hello', 'World', '!', '!']


In [0]:
#inserting items in the middle
x.insert(1,",")
print (x)

['Hello', ',', 'World', '!', '!']


In [0]:
#slicing
x[0:2] = ['Hello,', ' ']
print(x)

['Hello,', ' ', '.']


In [0]:
#lists Concatenation
x = ["Hello", ", "]
y = ["World", "!"]
print(x + y)

['Hello', ', ', 'World', '!']


In [0]:
a = [[1,2,3],2, 3,[1,1,1]]
b = a.copy()
b[1] = 100
b[0][1] = 100

In [0]:
#lists within lists
x = ["Hello", [", ", "World"], "!"]
print(x[1])
print(x[1][0])

[', ', 'World']
, 


### Tuples

In [0]:
x= ("Hello", ",")
y = "World", "!"  #This is also a tuple

In [0]:
#indexing
print(x[0])

#slicing
print (x[0:2])

#concatenating
print (x + y)

Hello
('Hello', ',')
('Hello', ',', 'World', '!')


In [0]:
#tuples are immutable 
x[0] = "s"

TypeError: 'tuple' object does not support item assignment

In [0]:
# but elements are mutable
x = ([1,2,3], "s")
x[0][0] = "a"
x

(['a', 2, 3], 's')

In [0]:
#unpacking tuples
var1, var2 = x
print(var1)
print(var2)

Hello
,


In [0]:
x = ([1,2,3], "s")
x

([1, 2, 3], 's')

### Sets

In [0]:
#sets are unordered and don't contain duplicates
x = set([1,2,3,1,2])
y = set("Hello")
print(x)
print(y)

{1, 2, 3}
{'H', 'e', 'l', 'o'}


In [21]:
x = set([1,2,3])
y = set([2,4,6])

#union
print (x | y)

#intersection
print (x & y)

#difference
print (x - y)

#symmetric difference
print (x ^ y)

{1, 2, 3, 4, 6}
{2}
{1, 3}
{1, 3, 4, 6}


In [22]:
#single items can be added using add(), multiple items can be added using update()
x.add(4)
y.update([6,8,10])
print(x)
print(y)

{1, 2, 3, 4}
{2, 4, 6, 8, 10}


In [0]:
#items can be removed using remove()
x.remove(3)
print(x)

{1, 2, 4}


### Dictionaries

In [0]:
#dictionary initialization
student = {"name" : "Ahmed", "id":20150001, "courses":["CIE 417", "CIE 418", "CIE 419"]}

#accessing members
print(student["name"])

Ahmed


In [0]:
#check for a dictionary member, and add it if it is not found
if "GPA" in student:
    print(student)
else:
    student["GPA"] = 1.00
    print(student)

{'name': 'Ahmed', 'id': 20150001, 'courses': ['CIE 417', 'CIE 418', 'CIE 419'], 0: 'as', 'GPA': 1.0}


In [0]:
from collections import defaultdict

a = defaultdict(lambda: 5)
a['first']

5

In [0]:
#get() function returns the value if found, or return a default value if not
name = student.get("name", "Mohamed")
number = student.get("number", "01000000000")
print(name,number)

Ahmed 01000000000


In [0]:
student["number"] = int("010012")
student

{'name': 'Ahmed',
 'id': 20150001,
 'courses': ['CIE 417', 'CIE 418', 'CIE 419'],
 0: 'as',
 'GPA': 1.0,
 'number': 10012}

In [0]:
#delete dictionary member
del student["GPA"]
print(student)

{'name': 'Ahmed', 'id': 20150001, 'courses': ['CIE 417', 'CIE 418', 'CIE 419'], 0: 'as', 'number': 10012}


In [0]:
#get a list of dictionary keys using list(student)
print (list(student))

['name', 'id', 'courses', 0, 'number']


In [0]:
student["number"] = None
student

{'name': 'Ahmed',
 'id': 20150001,
 'courses': ['CIE 417', 'CIE 418', 'CIE 419'],
 0: 'as',
 'number': None}

In [0]:
list(student.values())

['Ahmed', 20150001, ['CIE 417', 'CIE 418', 'CIE 419'], 'as', None]

### Iteration

In [0]:
#while loop
x = 5
while x:
    print(x)
    x -= 1

5
4
3
2
1


In [0]:
#for loop using range
for i in range(6):
    print(i,end=" ")
    
print("")
for i in range(5, 11):
    print(i,end=" ")
    
print("")
for i in range(0, 11, 2):
    print(i,end=" ")

0 1 2 3 4 5 
5 6 7 8 9 10 
0 2 4 6 8 10 

In [0]:
#iterating over iterables

#iterating over the characters of a string
x = "Hello"
for c in x:
    print (c, end=" ")
    
#iterating over a list
print("\n")
x = ["W", "o", "r", "l", "d"]
for c in x:
    print (c, end=" ")
    
#iterating over a dictionary
print("\n")
student = {"name" : "Ahmed", "id":20150001, "courses":["CIE 417", "CIE 418", "CIE 419"]}
for key in student:
    print (key, student[key])
    
#iterating over a list of tuples
print("\n")
student = [("Ahmed", 20150001, ["CIE 417", "CIE 418", "CIE 419"]), ("Mohamed", 20150002, ["CIE 417", "CIE 418", "CIE 419"])]
for name, uni_id, courses in student:
    print (name, uni_id, courses)

H e l l o 

W o r l d 

name Ahmed
id 20150001
courses ['CIE 417', 'CIE 418', 'CIE 419']


Ahmed 20150001 ['CIE 417', 'CIE 418', 'CIE 419']
Mohamed 20150002 ['CIE 417', 'CIE 418', 'CIE 419']


In [0]:
student = {"name" : "Ahmed", "id":20150001, "courses":["CIE 417", "CIE 418", "CIE 419"]}
for key, value in student.items():
    print (key, value)

name Ahmed
id 20150001
courses ['CIE 417', 'CIE 418', 'CIE 419']


In [0]:
#list comprehension, for example create a list of even numbers as strings
y = [str(i) for i in range(20) if i%2==0]
print(y)

['0', '2', '4', '6', '8', '10', '12', '14', '16', '18']


### Functions

In [0]:
def power(x, y=2): #y has a default value
    result = x**y
    return result

Result = power(3,3)
print (Result)

Result = power(3) #use default value of y
print (Result)

Result = power(x=3,y=3) #to remove ambiguities
print (Result)

27
9
27


In [0]:
#we can choose what parameters to use if they have default values
def date(year, month=1, day=1):
    print(f"{day:^10.2f}/{month}/{year}")
    
date(2018)
date(2018, day=20)
date(2018, day=20, month=9) #arbitrary order

ccc1.00ccc/1/2018
cc20.00ccc/1/2018
cc20.00ccc/9/2018


In [0]:
#return multiple outputs
def reverse_inputs(x,y):
    return y,x #a tuple

x = "x"
y = [1,2]
print (f"x = {x}, y = {y}")

x,y = reverse_inputs(x,y) #unpack resulting tuple
print (f"x = {x}, y = {y}")

result = reverse_inputs(x,y) #return as a tuple
print (result)

x = x, y = [1, 2]
x = [1, 2], y = x
('x', [1, 2])


In [0]:
#use global keyword inside function to change the global variable and not the local variable
x = ["s"]
def foo_local():
    x = ["y"]
    print("foo_local")
    print(f"local x = {x}")

foo_local()
print(f"global x = {x}\n")

x = ["s"]
def foo_global():
    global x
    x = ["y"]
    print("foo_local")
    print(f"local x = {x}")

foo_global()
print(f"global x = {x}\n")

foo_local
local x = ['y']
global x = ['s']

foo_local
local x = ['y']
global x = ['y']



In [0]:
x = [3]
def foo(x):
    x.append(5)
    print(x)
foo(x)
print(x)

[3, 5]
[3, 5]


### Classes

In [0]:
class Stack(object):
    def __init__(self, stack = None): #Initialize the stack
        if stack == None:
          self.stack = [ ]
        else:
          self.stack = stack
    def push(self,object):
        self.stack.append(object)
    def pop(self):
        return self.stack.pop()
    def length(self):
        return len(self.stack)
    def __len__(self):
        return len(self.stack)
    def __add__(self,other):
        newStack = self.stack.copy()
        newStack.append(other)
        return Stack(newStack)
    def __radd__(self,other):
        return self.__add__(other)
    def __str__(self):
        return f"({self.stack})"

In [0]:
x = Stack() #create a new object x
x.push("h")
x.push(["e","l"])
x.push(("l","o"))

In [0]:
y = 3+x

In [0]:
y.stack

['h', ['e', 'l'], ('l', 'o'), 3]

In [0]:
x.length()

3

In [0]:
len(x)

3

In [0]:
while x.length() > 0:
    print(x.pop())

('l', 'o')
['e', 'l']
h


In [0]:
# built-in functiona overloading
# https://realpython.com/operator-function-overloading/

### Numpy

In [0]:
import numpy as np

In [0]:
#array initialization from list
x = [[1,2,3],[4,5,6]]
x_np = np.array(x, dtype=np.float64)
print(type(x_np))
print(x_np)
print(f"shape: {x_np.shape}")

<class 'numpy.ndarray'>
[[1. 2. 3.]
 [4. 5. 6.]]
shape: (2, 3)


In [0]:
#array initialization from ones or zeros
x = np.ones((2,3))
y = np.zeros((3,3,2))
print(x)
print(f"shape: {x.shape}\n")
print(y)
print(f"shape: {y.shape}\n")

[[1. 1. 1.]
 [1. 1. 1.]]
shape: (2, 3)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
shape: (3, 3, 2)



In [0]:
x.dtype

dtype('float64')

In [0]:
#initialization from identity
x = np.eye(4)
y = np.identity(4)
print(x)
print("")
print(y)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [0]:
#np.arange is similar to the normal range
print (np.arange(0,10,2))

array([0, 2, 4, 6, 8])

In [0]:
#casting
x = np.array(["1","2","3"])
print(x)
x = x.astype(np.int32)
print(x)

['1' '2' '3']
[1 2 3]


In [0]:
#Arithematic operations between equal-sized arrays
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,2,2],[3,3,3]])

print(x*y)
print()
print(x+y)
print()
print(x-y)
print()
print(x/y)
print()
print(x**y)

[[ 2  4  6]
 [12 15 18]]

[[3 4 5]
 [7 8 9]]

[[-1  0  1]
 [ 1  2  3]]

[[0.5        1.         1.5       ]
 [1.33333333 1.66666667 2.        ]]

[[  1   4   9]
 [ 64 125 216]]


In [0]:
#Arithematic operations between arrays and scalars
x = np.array([[1,2,3],[4,5,6]])

print(x*2)
print()
print(x+2)
print()
print(2-x)
print()
print(2/x)
print()
print(x**2)

[[ 2  4  6]
 [ 8 10 12]]

[[3 4 5]
 [6 7 8]]

[[ 1  0 -1]
 [-2 -3 -4]]

[[2.         1.         0.66666667]
 [0.5        0.4        0.33333333]]

[[ 1  4  9]
 [16 25 36]]


In [0]:
#array slices are just views and not copies (not for lists)
x = np.ones((2,3,4))
print(x, end="\n\n\n")

x_slice = x[0,:2,1:] # 1: means from 1 till the end, :2 means from the beginning till 2
x_slice[:] = 10   #changing view(x_slice) changes original x
print(x)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


[[[ 1. 10. 10. 10.]
  [ 1. 10. 10. 10.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]]


In [0]:
#array.copy() creates a copy
x = np.ones((2,3,4))
print(x, end="\n\n\n")

x_slice = x[0,:2,1:].copy()
x_slice[:] = 10   #changing copy doesn't change original x
print(x)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [0]:
#transposing
x = np.arange(16).reshape((4,4))
print(x, end='\n\n')
print(x.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [0]:
x = np.arange(16).reshape((4,4))
x.reshape(2,2,-1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [0]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [0]:
#inverse
from numpy.linalg import inv
x = np.random.randn(4,4)
print(x, end='\n\n')
print(inv(x))

[[-0.23930712 -1.28435814 -0.27368768  0.0447967 ]
 [ 0.18539207  0.01663761  1.1514156   1.53449588]
 [-0.78730674 -0.74409676 -1.75035204  0.21111929]
 [-0.70324217 -0.10095388 -1.91615484  0.66550451]]

[[ 4.40036684 -1.6216602  -8.46293201  6.12767768]
 [-1.28879112  0.16458302  0.96557883 -0.59905032]
 [-1.36985951  0.69827661  2.70231619 -2.37511307]
 [ 0.51021765  0.32186342 -1.01570388  1.04834829]]


In [0]:
x = np.array([[1,1],[0,0]])

In [0]:
inv(x)

In [0]:
#determinant
x = np.random.randint(5, size=(3,3))
print(x)
np.linalg.det(x)

[[3 1 2]
 [2 1 0]
 [4 3 2]]


6.0

In [0]:
#trace
x = np.random.randint(5, size=(3,3))
print(x)
np.trace(x)

[[0 3 4]
 [3 4 4]
 [1 0 2]]


6

In [0]:
#eigenvalues and eigenvectors
x = np.random.randn(3,3)
print(x, end='\n\n')
eigenvalues, eigenvectors = np.linalg.eig(x)
print(f"eigenvalues = {eigenvalues}\ncorresponding eigenvectors = \n{eigenvectors}")

[[ 0.6483711   0.2199622  -1.16126007]
 [ 0.02669981  0.03393603 -1.22005731]
 [-1.15307105 -2.15821486  1.11992944]]

eigenvalues = [ 2.7758426   0.36542654 -1.33903258]
corresponding eigenvectors = 
[[-0.47522548 -0.89279504  0.34350019]
 [-0.36155588  0.4293791   0.62009506]
 [ 0.80214593 -0.13620061  0.70532952]]


In [0]:
#solve
a = np.array([[1,2,3],[2,3,5],[3,1,4]])
b = np.array([1,2,3])
x = np.linalg.solve(a,b)
print(f"{a} x {x} = {b}")

[[1 2 3]
 [2 3 5]
 [3 1 4]] x [ 0.65384615 -0.34615385  0.34615385] = [1 2 3]


In [0]:
#least square solution for y = wx + b
x = np.array([0, 1, 2, 3])
A = np.vstack([x, np.ones(len(x))]).T #include the bias term in A
y = np.array([-1, 0.2, 0.9, 2.1])

w, b = np.linalg.lstsq(A,y, rcond=None)[0]
print(round(w,2),round(b,2))

1.0 -0.95


### Resources
* https://docs.python.org/3/tutorial/introduction.html
* Python for Data Analysis by Wes McKinney (1st Edition)
* Python Essential Reference by David Beazley (4th Edition)
* https://pandas.pydata.org/pandas-docs/stable/10min.html (for a pandas quick tutorial)
* https://nlp.stanford.edu/IR-book/html/htmledition/linear-algebra-review-1.html